version: '3.5'

services:
  postgres:
    container_name: nest-auth-micro
    image: postgres:latest
    environment:
      POSTGRES_USER: phamphuong
      POSTGRES_PASSWORD: 21102001
      POSTGRES_DB: nest-auth-micro
      PGDATA: /data/postgres
    volumes:
      - postgres-db:/data/postgres
    ports:
      - "5432:5432"


volumes:
  postgres-db:
    driver: local
